//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proectitog
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProductInStockbaseEntities : DbContext
    {
        public ProductInStockbaseEntities()
            : base("name=ProductInStockbaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Intakee> Intakee { get; set; }
        public virtual DbSet<ProductIntake> ProductIntake { get; set; }
        public virtual DbSet<Productt> Productt { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
    }
}
