//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proectitog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productt
    {
        public int SerialNumber { get; set; }
        public string Name { get; set; }
        public byte[] MainImage { get; set; }
        public int UnitId { get; set; }
        public int Count { get; set; }
    }
}
